# Generated by Django 3.2.5 on 2022-01-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0019_alter_machinenotifecation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinenotifecation',
            name='notifeaction_type',
            field=models.IntegerField(choices=[(1, 'موعد دفع العربون'), (2, 'موعد دفع باقي المبلغ'), (3, 'موعد استلام البضاعة'), (4, 'موعد دفع الضرائب')], default=0, verbose_name='نوع الاشعار'),
        ),
    ]
