# Generated by Django 3.2.5 on 2022-01-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0020_alter_machinenotifecation_notifeaction_type'),
        ('Machines', '0021_auto_20220106_2301'),
    ]

    operations = [
    ]
