# Generated by Django 3.2.5 on 2022-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0023_alter_machinenotifecation_notifeaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesorderproducts',
            name='product_price',
            field=models.FloatField(default=0, null=True, verbose_name='سعر الشراء الكلي'),
        ),
    ]
