# Generated by Django 3.2.5 on 2022-01-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Treasury', '0006_auto_20211214_1623'),
        ('Machines', '0023_alter_machinenotifecation_notifeaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('invoice_product_type', models.IntegerField(choices=[(1, 'مبيعات ماكينات'), (2, 'مبيعات قطع غيار')], default=0, verbose_name='نوع المنتجات')),
                ('invoice_type', models.IntegerField(choices=[(1, 'فاتورة مبيعات'), (2, 'فاتورة مرتجع مبيعات'), (3, 'بيان أسعار')], default=0, verbose_name='نوع الفاتورة')),
                ('customer', models.CharField(max_length=255, verbose_name='العميل')),
                ('total', models.FloatField(default=0.0, verbose_name='إجمالي الفاتورة')),
                ('discount', models.FloatField(default=0.0, verbose_name='الخصم')),
                ('after_discount', models.FloatField(default=0.0, verbose_name='بعد الخصم')),
                ('invoice_discount', models.FloatField(default=0.0, verbose_name='خصم خاص علي الفاتورة')),
                ('overall', models.FloatField(default=0.0, verbose_name='إجمالي')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('saved', models.BooleanField(default=False, verbose_name='حفظ')),
                ('paid', models.BooleanField(default=False, verbose_name='دفع')),
                ('paid_value', models.FloatField(default=0.0, verbose_name='القيمة المدفوعة')),
                ('residual_value', models.FloatField(default=0.0, verbose_name='القيمة المتبقية')),
                ('residual_value_pay_date', models.DateField(null=True, verbose_name='تاريخ اكمال الدفع')),
                ('out_of_warehouse', models.BooleanField(default=False, verbose_name='خروج من المخزن')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('profit', models.FloatField(default=0.0, verbose_name='الربح')),
                ('return_inv_id', models.IntegerField(default=0, verbose_name='رقم الفاتورة الأصلية')),
                ('pay_type', models.CharField(max_length=255, verbose_name='نوع الدفع')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='منشئ الفاتورة')),
                ('treasury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Treasury.worktreasury', verbose_name='الخزينة')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machines.machineswarehouses', verbose_name='المخزن')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0.0, verbose_name='سعر البيع')),
                ('quantity', models.FloatField(default=1.0, verbose_name='الكمية')),
                ('total_price', models.FloatField(default=0.0, verbose_name='إجمالي')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='ملاحظات')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف المنتج من الفاتورة')),
                ('profit', models.FloatField(default=0.0, verbose_name='الربح')),
                ('expected_profit', models.FloatField(default=0.0, verbose_name='الربح المتوقع')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoice', verbose_name='الفاتورة')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machines.machinesnames', verbose_name='الصنف')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0, verbose_name='الكمية')),
                ('undo', models.FloatField(default=0, verbose_name='الكمية المرتجعة')),
                ('balance', models.FloatField(default=1.0, verbose_name='الرصيد')),
                ('purchase_price', models.FloatField(default=0.0, verbose_name='سعر البيع')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoiceitem', verbose_name='عنصر الفاتورة')),
            ],
        ),
    ]
