# Generated by Django 3.2.5 on 2022-01-20 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 20), verbose_name='التاريخ'),
        ),
    ]
