# Generated by Django 3.2.5 on 2022-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_alter_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='after_discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='expected_profit',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='profit',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='overall',
            field=models.FloatField(default=0.0, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='قيمة الفاتورة'),
        ),
    ]
